@file:Suppress("unused")

package com.iroid.savvy.rd

// Normally generated by the Android build from app/build.gradle.kts and res/.
object BuildConfig {
    const val BACKEND_URL = "http://192.168.1.10:3000"
    const val CARD_DOMAIN = "go.savvy.test"
}

object R {
    object string {
        const val accessibility_description = 1
        const val prominent_disclosure = 2
    }
}
